version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cleandb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cleandb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/prod/combined.Dockerfile
    ports:
      - "8000:8000"  # Backend API
      - "3000:3000"  # Frontend
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: