version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cleandb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-vector-extension.sql:/docker-entrypoint-initdb.d/init-vector-extension.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cleandb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/dev/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy 
    command: >
      sh -c "
        sleep 5 &&  # Additional safety delay
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/dev/frontend.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://localhost:8000
      - NODE_ENV=development
    command: npm run dev -- --host # --host to make it accessible outside container
    depends_on:
      - backend

volumes:
  postgres_data: