"""Add saved property to documents

Revision ID: 48b69b0e653a
Revises: 58016d461483
Create Date: 2025-01-03 14:39:54.791455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b69b0e653a'
down_revision = '58016d461483'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('saved', sa.Boolean(), nullable=True))
    # op.drop_index('ix_tag_name', table_name='tag')
    # op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_tag_name'), table_name='tag')
    # op.create_index('ix_tag_name', 'tag', ['name'], unique=False)
    op.drop_column('document', 'saved')
    # ### end Alembic commands ###