"""Add saved_documents association table

Revision ID: 58016d461483
Revises: 978f296a47c3
Create Date: 2025-01-02 22:41:13.474467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58016d461483'
down_revision = '978f296a47c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_documents',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_documents')
    # ### end Alembic commands ###