"""Fill whitelisted domain table

Revision ID: 9ea8752fcf9c
Revises: a9e6befbf093
Create Date: 2025-01-10 22:08:26.151550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea8752fcf9c'
down_revision = 'a9e6befbf093'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tag_name', table_name='tag')
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    
    # Bulk insert into whitelisted_domain table
    whitelisted_domain_table = sa.table('whitelisted_domain',
        sa.column('id', sa.Integer),
        sa.column('domain', sa.String),
    )

    op.bulk_insert(whitelisted_domain_table,
        [
            {'id': 1, 'domain': 'cleancookingalliance.org'},
            {'id': 2, 'domain': 'who.int'},
            {'id': 3, 'domain': 'worldbank.org'},
            {'id': 4, 'domain': 'seforall.org'},
            {'id': 5, 'domain': 'mecs.org.uk'},
            {'id': 6, 'domain': 'sciencedirect.com'},
            {'id': 7, 'domain': 'mdpi.com'},
        ]
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.create_index('ix_tag_name', 'tag', ['name'], unique=False)
    
    op.execute("DELETE FROM whitelisted_domain WHERE domain IN ('cleancookingalliance.org', 'who.int', 'worldbank.org', 'seforall.org', 'mecs.org.uk', 'sciencedirect.com', 'mdpi.com')")
    # ### end Alembic commands ###