"""Added whitelisted domain table

Revision ID: bdc2e161d9af
Revises: 978f296a47c3
Create Date: 2025-01-05 23:06:21.743573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc2e161d9af'
down_revision = '978f296a47c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whitelisted_domain',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_whitelisted_domain_id'), 'whitelisted_domain', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whitelisted_domain_id'), table_name='whitelisted_domain')
    op.drop_table('whitelisted_domain')
    # ### end Alembic commands ###