# backend/app/initialize_tags.py

from sqlalchemy.orm import Session
from app.crud.crud_tag import tag as crud_tag
from app.schemas.tag import TagCreate

def initialize_tags(db: Session):
    tags = [
        # Region Tags
        {"name": "South Asia", "category": "REGION"},
        {"name": "East Asia and Pacific", "category": "REGION"},
        {"name": "Europe", "category": "REGION"},
        {"name": "North America", "category": "REGION"},
        {"name": "Latin America and Caribbean", "category": "REGION"},
        {"name": "Global", "category": "REGION"},
        {"name": "Sub-Saharan Africa", "category": "REGION"},
        # Country Tags
        {"name": "Afghanistan", "category": "COUNTRY"},
        {"name": "Albania", "category": "COUNTRY"},
        {"name": "Algeria", "category": "COUNTRY"},
        {"name": "Andorra", "category": "COUNTRY"},
        {"name": "Angola", "category": "COUNTRY"},
        {"name": "Antigua and Barbuda", "category": "COUNTRY"},
        {"name": "Argentina", "category": "COUNTRY"},
        {"name": "Armenia", "category": "COUNTRY"},
        {"name": "Australia", "category": "COUNTRY"},
        {"name": "Austria", "category": "COUNTRY"},
        {"name": "Azerbaijan", "category": "COUNTRY"},
        {"name": "Bahamas", "category": "COUNTRY"},
        {"name": "Bahrain", "category": "COUNTRY"},
        {"name": "Bangladesh", "category": "COUNTRY"},
        {"name": "Barbados", "category": "COUNTRY"},
        {"name": "Belarus", "category": "COUNTRY"},
        {"name": "Belgium", "category": "COUNTRY"},
        {"name": "Belize", "category": "COUNTRY"},
        {"name": "Benin", "category": "COUNTRY"},
        {"name": "Bhutan", "category": "COUNTRY"},
        {"name": "Bolivia", "category": "COUNTRY"},
        {"name": "Bosnia and Herzegovina", "category": "COUNTRY"},
        {"name": "Botswana", "category": "COUNTRY"},
        {"name": "Brazil", "category": "COUNTRY"},
        {"name": "Brunei", "category": "COUNTRY"},
        {"name": "Bulgaria", "category": "COUNTRY"},
        {"name": "Burkina Faso", "category": "COUNTRY"},
        {"name": "Burundi", "category": "COUNTRY"},
        {"name": "Côte d'Ivoire", "category": "COUNTRY"},
        {"name": "Cabo Verde", "category": "COUNTRY"},
        {"name": "Cambodia", "category": "COUNTRY"},
        {"name": "Cameroon", "category": "COUNTRY"},
        {"name": "Canada", "category": "COUNTRY"},
        {"name": "Central African Republic", "category": "COUNTRY"},
        {"name": "Chad", "category": "COUNTRY"},
        {"name": "Chile", "category": "COUNTRY"},
        {"name": "China", "category": "COUNTRY"},
        {"name": "Colombia", "category": "COUNTRY"},
        {"name": "Comoros", "category": "COUNTRY"},
        {"name": "Congo (Congo-Brazzaville)", "category": "COUNTRY"},
        {"name": "Costa Rica", "category": "COUNTRY"},
        {"name": "Croatia", "category": "COUNTRY"},
        {"name": "Cuba", "category": "COUNTRY"},
        {"name": "Cyprus", "category": "COUNTRY"},
        {"name": "Czechia (Czech Republic)", "category": "COUNTRY"},
        {"name": "Democratic Republic of the Congo", "category": "COUNTRY"},
        {"name": "Denmark", "category": "COUNTRY"},
        {"name": "Djibouti", "category": "COUNTRY"},
        {"name": "Dominica", "category": "COUNTRY"},
        {"name": "Dominican Republic", "category": "COUNTRY"},
        {"name": "Ecuador", "category": "COUNTRY"},
        {"name": "Egypt", "category": "COUNTRY"},
        {"name": "El Salvador", "category": "COUNTRY"},
        {"name": "Equatorial Guinea", "category": "COUNTRY"},
        {"name": "Eritrea", "category": "COUNTRY"},
        {"name": "Estonia", "category": "COUNTRY"},
        {"name": "Eswatini (fmr. 'Swaziland')", "category": "COUNTRY"},
        {"name": "Ethiopia", "category": "COUNTRY"},
        {"name": "Fiji", "category": "COUNTRY"},
        {"name": "Finland", "category": "COUNTRY"},
        {"name": "France", "category": "COUNTRY"},
        {"name": "Gabon", "category": "COUNTRY"},
        {"name": "Gambia", "category": "COUNTRY"},
        {"name": "Georgia", "category": "COUNTRY"},
        {"name": "Germany", "category": "COUNTRY"},
        {"name": "Ghana", "category": "COUNTRY"},
        {"name": "Greece", "category": "COUNTRY"},
        {"name": "Grenada", "category": "COUNTRY"},
        {"name": "Guatemala", "category": "COUNTRY"},
        {"name": "Guinea", "category": "COUNTRY"},
        {"name": "Guinea-Bissau", "category": "COUNTRY"},
        {"name": "Guyana", "category": "COUNTRY"},
        {"name": "Haiti", "category": "COUNTRY"},
        {"name": "Holy See", "category": "COUNTRY"},
        {"name": "Honduras", "category": "COUNTRY"},
        {"name": "Hungary", "category": "COUNTRY"},
        {"name": "Iceland", "category": "COUNTRY"},
        {"name": "India", "category": "COUNTRY"},
        {"name": "Indonesia", "category": "COUNTRY"},
        {"name": "Iran", "category": "COUNTRY"},
        {"name": "Iraq", "category": "COUNTRY"},
        {"name": "Ireland", "category": "COUNTRY"},
        {"name": "Israel", "category": "COUNTRY"},
        {"name": "Italy", "category": "COUNTRY"},
        {"name": "Jamaica", "category": "COUNTRY"},
        {"name": "Japan", "category": "COUNTRY"},
        {"name": "Jordan", "category": "COUNTRY"},
        {"name": "Kazakhstan", "category": "COUNTRY"},
        {"name": "Kenya", "category": "COUNTRY"},
        {"name": "Kiribati", "category": "COUNTRY"},
        {"name": "Kuwait", "category": "COUNTRY"},
        {"name": "Kyrgyzstan", "category": "COUNTRY"},
        {"name": "Laos", "category": "COUNTRY"},
        {"name": "Latvia", "category": "COUNTRY"},
        {"name": "Lebanon", "category": "COUNTRY"},
        {"name": "Lesotho", "category": "COUNTRY"},
        {"name": "Liberia", "category": "COUNTRY"},
        {"name": "Libya", "category": "COUNTRY"},
        {"name": "Liechtenstein", "category": "COUNTRY"},
        {"name": "Lithuania", "category": "COUNTRY"},
        {"name": "Luxembourg", "category": "COUNTRY"},
        {"name": "Madagascar", "category": "COUNTRY"},
        {"name": "Malawi", "category": "COUNTRY"},
        {"name": "Malaysia", "category": "COUNTRY"},
        {"name": "Maldives", "category": "COUNTRY"},
        {"name": "Mali", "category": "COUNTRY"},
        {"name": "Malta", "category": "COUNTRY"},
        {"name": "Marshall Islands", "category": "COUNTRY"},
        {"name": "Mauritania", "category": "COUNTRY"},
        {"name": "Mauritius", "category": "COUNTRY"},
        {"name": "Mexico", "category": "COUNTRY"},
        {"name": "Micronesia", "category": "COUNTRY"},
        {"name": "Moldova", "category": "COUNTRY"},
        {"name": "Monaco", "category": "COUNTRY"},
        {"name": "Mongolia", "category": "COUNTRY"},
        {"name": "Montenegro", "category": "COUNTRY"},
        {"name": "Morocco", "category": "COUNTRY"},
        {"name": "Mozambique", "category": "COUNTRY"},
        {"name": "Myanmar (formerly Burma)", "category": "COUNTRY"},
        {"name": "Namibia", "category": "COUNTRY"},
        {"name": "Nauru", "category": "COUNTRY"},
        {"name": "Nepal", "category": "COUNTRY"},
        {"name": "Netherlands", "category": "COUNTRY"},
        {"name": "New Zealand", "category": "COUNTRY"},
        {"name": "Nicaragua", "category": "COUNTRY"},
        {"name": "Niger", "category": "COUNTRY"},
        {"name": "Nigeria", "category": "COUNTRY"},
        {"name": "North Korea", "category": "COUNTRY"},
        {"name": "North Macedonia", "category": "COUNTRY"},
        {"name": "Norway", "category": "COUNTRY"},
        {"name": "Oman", "category": "COUNTRY"},
        {"name": "Pakistan", "category": "COUNTRY"},
        {"name": "Palau", "category": "COUNTRY"},
        {"name": "Palestine State", "category": "COUNTRY"},
        {"name": "Panama", "category": "COUNTRY"},
        {"name": "Papua New Guinea", "category": "COUNTRY"},
        {"name": "Paraguay", "category": "COUNTRY"},
        {"name": "Peru", "category": "COUNTRY"},
        {"name": "Philippines", "category": "COUNTRY"},
        {"name": "Poland", "category": "COUNTRY"},
        {"name": "Portugal", "category": "COUNTRY"},
        {"name": "Qatar", "category": "COUNTRY"},
        {"name": "Romania", "category": "COUNTRY"},
        {"name": "Russia", "category": "COUNTRY"},
        {"name": "Rwanda", "category": "COUNTRY"},
        {"name": "Saint Kitts and Nevis", "category": "COUNTRY"},
        {"name": "Saint Lucia", "category": "COUNTRY"},
        {"name": "Saint Vincent and the Grenadines", "category": "COUNTRY"},
        {"name": "Samoa", "category": "COUNTRY"},
        {"name": "San Marino", "category": "COUNTRY"},
        {"name": "Sao Tome and Principe", "category": "COUNTRY"},
        {"name": "Saudi Arabia", "category": "COUNTRY"},
        {"name": "Senegal", "category": "COUNTRY"},
        {"name": "Serbia", "category": "COUNTRY"},
        {"name": "Seychelles", "category": "COUNTRY"},
        {"name": "Sierra Leone", "category": "COUNTRY"},
        {"name": "Singapore", "category": "COUNTRY"},
        {"name": "Slovakia", "category": "COUNTRY"},
        {"name": "Slovenia", "category": "COUNTRY"},
        {"name": "Solomon Islands", "category": "COUNTRY"},
        {"name": "Somalia", "category": "COUNTRY"},
        {"name": "South Africa", "category": "COUNTRY"},
        {"name": "South Korea", "category": "COUNTRY"},
        {"name": "South Sudan", "category": "COUNTRY"},
        {"name": "Spain", "category": "COUNTRY"},
        {"name": "Sri Lanka", "category": "COUNTRY"},
        {"name": "Sudan", "category": "COUNTRY"},
        {"name": "Suriname", "category": "COUNTRY"},
        {"name": "Sweden", "category": "COUNTRY"},
        {"name": "Switzerland", "category": "COUNTRY"},
        {"name": "Syria", "category": "COUNTRY"},
        {"name": "Tajikistan", "category": "COUNTRY"},
        {"name": "Tanzania", "category": "COUNTRY"},
        {"name": "Thailand", "category": "COUNTRY"},
        {"name": "Timor-Leste", "category": "COUNTRY"},
        {"name": "Togo", "category": "COUNTRY"},
        {"name": "Tonga", "category": "COUNTRY"},
        {"name": "Trinidad and Tobago", "category": "COUNTRY"},
        {"name": "Tunisia", "category": "COUNTRY"},
        {"name": "Turkey", "category": "COUNTRY"},
        {"name": "Turkmenistan", "category": "COUNTRY"},
        {"name": "Tuvalu", "category": "COUNTRY"},
        {"name": "Uganda", "category": "COUNTRY"},
        {"name": "Ukraine", "category": "COUNTRY"},
        {"name": "United Arab Emirates", "category": "COUNTRY"},
        {"name": "United Kingdom", "category": "COUNTRY"},
        {"name": "United States of America", "category": "COUNTRY"},
        {"name": "Uruguay", "category": "COUNTRY"},
        {"name": "Uzbekistan", "category": "COUNTRY"},
        {"name": "Vanuatu", "category": "COUNTRY"},
        {"name": "Venezuela", "category": "COUNTRY"},
        {"name": "Vietnam", "category": "COUNTRY"},
        {"name": "Yemen", "category": "COUNTRY"},
        {"name": "Zambia", "category": "COUNTRY"},
        {"name": "Zimbabwe", "category": "COUNTRY"},
        # Topic Tags
        {"name": "Adoption", "category": "TOPIC"},
        {"name": "Carbon Finance", "category": "TOPIC"},
        {"name": "Consumer Finance", "category": "TOPIC"},
        {"name": "Consumer Segmentation", "category": "TOPIC"},
        {"name": "Fuels", "category": "TOPIC"},
        {"name": "Livelihoods", "category": "TOPIC"},
        {"name": "Monitoring and Evaluation", "category": "TOPIC"},
        {"name": "Standards", "category": "TOPIC"},
        {"name": "Testing (actual testing of technologies/stoves/fuels)", "category": "TOPIC"},
        # Technology Tags
        {"name": "Biodigesters", "category": "TECHNOLOGY"},
        {"name": "Briquette Type Fuels", "category": "TECHNOLOGY"},
        {"name": "Electric cooking", "category": "TECHNOLOGY"},
        {"name": "Ethanol", "category": "TECHNOLOGY"},
        {"name": "Improved Biomass Stoves", "category": "TECHNOLOGY"},
        {"name": "LPG", "category": "TECHNOLOGY"},
        {"name": "Pellets & Gasifier Stoves", "category": "TECHNOLOGY"},
        # Product Lifecycle Tags
        {"name": "Introduction", "category": "PRODUCT_LIFECYCLE"},
        {"name": "Growth", "category": "PRODUCT_LIFECYCLE"},
        {"name": "Maturity", "category": "PRODUCT_LIFECYCLE"},
        {"name": "Decline", "category": "PRODUCT_LIFECYCLE"},
        # Customer Journey Tags
        {"name": "Awareness", "category": "CUSTOMER_JOURNEY"},
        {"name": "Consideration", "category": "CUSTOMER_JOURNEY"},
        {"name": "Intention", "category": "CUSTOMER_JOURNEY"},
        {"name": "Acquisition", "category": "CUSTOMER_JOURNEY"},
        {"name": "First Use", "category": "CUSTOMER_JOURNEY"},
        {"name": "User Experience", "category": "CUSTOMER_JOURNEY"},
        {"name": "Post-Purchase Support", "category": "CUSTOMER_JOURNEY"},
        {"name": "Advocacy/Referral", "category": "CUSTOMER_JOURNEY"},
        {"name": "End of life", "category": "CUSTOMER_JOURNEY"},
    ]

    for tag_data in tags:
        existing_tag = crud_tag.get_by_name(db, name=tag_data["name"])
        if not existing_tag:
            tag_in = TagCreate(name=tag_data["name"], category=tag_data["category"].lower())
            crud_tag.create(db, obj_in=tag_in)